// Generated from Entire Graph. Run npm run graph:generate to refresh.
import type { GraphData } from "./mock-data";

export const entireGraphData: GraphData = {
  nodes: [
    {
      id: "src/components/ui/accordion.tsx",
      label: "accordion.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/accordion.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 1,
      dependentCount: 0,
      x: 80,
      y: 70,
    },
    {
      id: "src/components/ui/alert-dialog.tsx",
      label: "alert-dialog.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/alert-dialog.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 2,
      dependentCount: 0,
      x: 190,
      y: 70,
    },
    {
      id: "src/components/ui/alert.tsx",
      label: "alert.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/alert.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 1,
      dependentCount: 0,
      x: 300,
      y: 70,
    },
    {
      id: "src/components/ui/aspect-ratio.tsx",
      label: "aspect-ratio.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/aspect-ratio.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 0,
      dependentCount: 0,
      x: 410,
      y: 70,
    },
    {
      id: "src/components/ui/avatar.tsx",
      label: "avatar.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/avatar.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 14,
      dependencyCount: 1,
      dependentCount: 2,
      x: 520,
      y: 70,
    },
    {
      id: "src/components/ui/badge.tsx",
      label: "badge.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/badge.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 1,
      dependentCount: 0,
      x: 630,
      y: 70,
    },
    {
      id: "src/components/ui/breadcrumb.tsx",
      label: "breadcrumb.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/breadcrumb.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 1,
      dependentCount: 0,
      x: 740,
      y: 70,
    },
    {
      id: "src/components/ui/button.tsx",
      label: "button.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/button.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 35,
      dependencyCount: 1,
      dependentCount: 9,
      x: 850,
      y: 70,
    },
    {
      id: "src/components/ui/calendar.tsx",
      label: "calendar.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/calendar.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 2,
      dependentCount: 0,
      x: 80,
      y: 160,
    },
    {
      id: "src/components/ui/card.tsx",
      label: "card.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/card.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 1,
      dependentCount: 0,
      x: 190,
      y: 160,
    },
    {
      id: "src/components/ui/carousel.tsx",
      label: "carousel.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/carousel.tsx",
      complexity: 5,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 40,
      dependencyCount: 2,
      dependentCount: 0,
      x: 300,
      y: 160,
    },
    {
      id: "src/components/ui/chart.tsx",
      label: "chart.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/chart.tsx",
      complexity: 3,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 24,
      dependencyCount: 1,
      dependentCount: 0,
      x: 410,
      y: 160,
    },
    {
      id: "src/components/ui/checkbox.tsx",
      label: "checkbox.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/checkbox.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 1,
      dependentCount: 0,
      x: 520,
      y: 160,
    },
    {
      id: "src/components/ui/collapsible.tsx",
      label: "collapsible.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/collapsible.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 0,
      dependentCount: 0,
      x: 630,
      y: 160,
    },
    {
      id: "src/components/ui/command.tsx",
      label: "command.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/command.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 2,
      dependentCount: 0,
      x: 740,
      y: 160,
    },
    {
      id: "src/components/ui/context-menu.tsx",
      label: "context-menu.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/context-menu.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 1,
      dependentCount: 0,
      x: 850,
      y: 160,
    },
    {
      id: "src/components/ui/dialog.tsx",
      label: "dialog.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/dialog.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 11,
      dependencyCount: 1,
      dependentCount: 1,
      x: 80,
      y: 250,
    },
    {
      id: "src/components/ui/drawer.tsx",
      label: "drawer.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/drawer.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 1,
      dependentCount: 0,
      x: 190,
      y: 250,
    },
    {
      id: "src/components/ui/dropdown-menu.tsx",
      label: "dropdown-menu.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/dropdown-menu.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 1,
      dependentCount: 0,
      x: 300,
      y: 250,
    },
    {
      id: "src/components/ui/form.tsx",
      label: "form.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/form.tsx",
      complexity: 2,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 16,
      dependencyCount: 2,
      dependentCount: 0,
      x: 410,
      y: 250,
    },
    {
      id: "src/components/ui/hover-card.tsx",
      label: "hover-card.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/hover-card.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 1,
      dependentCount: 0,
      x: 520,
      y: 250,
    },
    {
      id: "src/components/ui/input-otp.tsx",
      label: "input-otp.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/input-otp.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 1,
      dependentCount: 0,
      x: 630,
      y: 250,
    },
    {
      id: "src/components/ui/input.tsx",
      label: "input.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/input.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 11,
      dependencyCount: 1,
      dependentCount: 1,
      x: 740,
      y: 250,
    },
    {
      id: "src/components/ui/label.tsx",
      label: "label.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/label.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 11,
      dependencyCount: 1,
      dependentCount: 1,
      x: 850,
      y: 250,
    },
    {
      id: "src/components/ui/menubar.tsx",
      label: "menubar.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/menubar.tsx",
      complexity: 2,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 16,
      dependencyCount: 1,
      dependentCount: 0,
      x: 80,
      y: 340,
    },
    {
      id: "src/components/ui/navigation-menu.tsx",
      label: "navigation-menu.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/navigation-menu.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 1,
      dependentCount: 0,
      x: 190,
      y: 340,
    },
    {
      id: "src/components/ui/pagination.tsx",
      label: "pagination.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/pagination.tsx",
      complexity: 2,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 16,
      dependencyCount: 2,
      dependentCount: 0,
      x: 300,
      y: 340,
    },
    {
      id: "src/components/ui/popover.tsx",
      label: "popover.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/popover.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 1,
      dependentCount: 0,
      x: 410,
      y: 340,
    },
    {
      id: "src/components/ui/progress.tsx",
      label: "progress.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/progress.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 1,
      dependentCount: 0,
      x: 520,
      y: 340,
    },
    {
      id: "src/components/ui/radio-group.tsx",
      label: "radio-group.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/radio-group.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 1,
      dependentCount: 0,
      x: 630,
      y: 340,
    },
    {
      id: "src/components/ui/resizable.tsx",
      label: "resizable.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/resizable.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 1,
      dependentCount: 0,
      x: 740,
      y: 340,
    },
    {
      id: "src/components/ui/scroll-area.tsx",
      label: "scroll-area.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/scroll-area.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 1,
      dependentCount: 0,
      x: 850,
      y: 340,
    },
    {
      id: "src/components/ui/select.tsx",
      label: "select.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/select.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 1,
      dependentCount: 0,
      x: 80,
      y: 430,
    },
    {
      id: "src/components/ui/separator.tsx",
      label: "separator.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/separator.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 11,
      dependencyCount: 1,
      dependentCount: 1,
      x: 190,
      y: 430,
    },
    {
      id: "src/components/ui/sheet.tsx",
      label: "sheet.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/sheet.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 1,
      dependentCount: 0,
      x: 300,
      y: 430,
    },
    {
      id: "src/components/ui/sidebar.tsx",
      label: "sidebar.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/sidebar.tsx",
      complexity: 3,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 24,
      dependencyCount: 7,
      dependentCount: 0,
      x: 410,
      y: 430,
    },
    {
      id: "src/components/ui/skeleton.tsx",
      label: "skeleton.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/skeleton.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 11,
      dependencyCount: 1,
      dependentCount: 1,
      x: 520,
      y: 430,
    },
    {
      id: "src/components/ui/slider.tsx",
      label: "slider.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/slider.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 1,
      dependentCount: 0,
      x: 630,
      y: 430,
    },
    {
      id: "src/components/ui/sonner.tsx",
      label: "sonner.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/sonner.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 0,
      dependentCount: 0,
      x: 740,
      y: 430,
    },
    {
      id: "src/components/ui/switch.tsx",
      label: "switch.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/switch.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 1,
      dependentCount: 0,
      x: 850,
      y: 430,
    },
    {
      id: "src/components/ui/table.tsx",
      label: "table.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/table.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 1,
      dependentCount: 0,
      x: 80,
      y: 520,
    },
    {
      id: "src/components/ui/tabs.tsx",
      label: "tabs.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/tabs.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 1,
      dependentCount: 0,
      x: 190,
      y: 520,
    },
    {
      id: "src/components/ui/textarea.tsx",
      label: "textarea.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/textarea.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 11,
      dependencyCount: 1,
      dependentCount: 1,
      x: 300,
      y: 520,
    },
    {
      id: "src/components/ui/toggle-group.tsx",
      label: "toggle-group.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/toggle-group.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 2,
      dependentCount: 0,
      x: 410,
      y: 520,
    },
    {
      id: "src/components/ui/toggle.tsx",
      label: "toggle.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/toggle.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 11,
      dependencyCount: 1,
      dependentCount: 1,
      x: 520,
      y: 520,
    },
    {
      id: "src/components/ui/tooltip.tsx",
      label: "tooltip.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/components/ui/tooltip.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 11,
      dependencyCount: 1,
      dependentCount: 1,
      x: 630,
      y: 520,
    },
    {
      id: "src/hooks/use-mobile.tsx",
      label: "use-mobile.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/hooks/use-mobile.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 11,
      dependencyCount: 0,
      dependentCount: 1,
      x: 740,
      y: 520,
    },
    {
      id: "src/lib/error-capture.ts",
      label: "error-capture.ts",
      type: "module",
      language: "TypeScript",
      path: "src/lib/error-capture.ts",
      complexity: 2,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 19,
      dependencyCount: 0,
      dependentCount: 1,
      x: 850,
      y: 520,
    },
    {
      id: "src/lib/error-page.ts",
      label: "error-page.ts",
      type: "module",
      language: "TypeScript",
      path: "src/lib/error-page.ts",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 14,
      dependencyCount: 0,
      dependentCount: 2,
      x: 80,
      y: 610,
    },
    {
      id: "src/lib/lovable-error-reporting.ts",
      label: "lovable-error-reporting.ts",
      type: "module",
      language: "TypeScript",
      path: "src/lib/lovable-error-reporting.ts",
      complexity: 3,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 27,
      dependencyCount: 0,
      dependentCount: 1,
      x: 190,
      y: 610,
    },
    {
      id: "src/lib/mock-data.ts",
      label: "mock-data.ts",
      type: "module",
      language: "TypeScript",
      path: "src/lib/mock-data.ts",
      complexity: 10,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 95,
      dependencyCount: 0,
      dependentCount: 5,
      x: 300,
      y: 610,
    },
    {
      id: "src/lib/trace-store.ts",
      label: "trace-store.ts",
      type: "module",
      language: "TypeScript",
      path: "src/lib/trace-store.ts",
      complexity: 2,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 22,
      dependencyCount: 1,
      dependentCount: 2,
      x: 410,
      y: 610,
    },
    {
      id: "src/lib/utils.ts",
      label: "utils.ts",
      type: "module",
      language: "TypeScript",
      path: "src/lib/utils.ts",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 95,
      dependencyCount: 0,
      dependentCount: 48,
      x: 520,
      y: 610,
    },
    {
      id: "src/routeTree.gen.ts",
      label: "routeTree.gen.ts",
      type: "module",
      language: "TypeScript",
      path: "src/routeTree.gen.ts",
      complexity: 10,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 80,
      dependencyCount: 8,
      dependentCount: 0,
      x: 630,
      y: 610,
    },
    {
      id: "src/router.tsx",
      label: "router.tsx",
      type: "module",
      language: "TypeScript",
      path: "src/router.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 11,
      dependencyCount: 0,
      dependentCount: 1,
      x: 740,
      y: 610,
    },
    {
      id: "src/routes/README.md",
      label: "README.md",
      type: "component",
      language: "Markdown",
      path: "src/routes/README.md",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 8,
      dependencyCount: 0,
      dependentCount: 0,
      x: 850,
      y: 610,
    },
    {
      id: "src/routes/__root.tsx",
      label: "__root.tsx",
      type: "component",
      language: "TypeScript",
      path: "src/routes/__root.tsx",
      complexity: 2,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 19,
      dependencyCount: 1,
      dependentCount: 1,
      x: 80,
      y: 700,
    },
    {
      id: "src/routes/analytics.tsx",
      label: "analytics.tsx",
      type: "component",
      language: "TypeScript",
      path: "src/routes/analytics.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 11,
      dependencyCount: 2,
      dependentCount: 1,
      x: 190,
      y: 700,
    },
    {
      id: "src/routes/explore.tsx",
      label: "explore.tsx",
      type: "component",
      language: "TypeScript",
      path: "src/routes/explore.tsx",
      complexity: 2,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 19,
      dependencyCount: 3,
      dependentCount: 1,
      x: 300,
      y: 700,
    },
    {
      id: "src/routes/impact.tsx",
      label: "impact.tsx",
      type: "component",
      language: "TypeScript",
      path: "src/routes/impact.tsx",
      complexity: 2,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 19,
      dependencyCount: 4,
      dependentCount: 1,
      x: 410,
      y: 700,
    },
    {
      id: "src/routes/index.tsx",
      label: "index.tsx",
      type: "component",
      language: "TypeScript",
      path: "src/routes/index.tsx",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 11,
      dependencyCount: 4,
      dependentCount: 1,
      x: 520,
      y: 700,
    },
    {
      id: "src/routes/sessions.tsx",
      label: "sessions.tsx",
      type: "component",
      language: "TypeScript",
      path: "src/routes/sessions.tsx",
      complexity: 2,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 19,
      dependencyCount: 5,
      dependentCount: 1,
      x: 630,
      y: 700,
    },
    {
      id: "src/server.ts",
      label: "server.ts",
      type: "module",
      language: "TypeScript",
      path: "src/server.ts",
      complexity: 2,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 16,
      dependencyCount: 2,
      dependentCount: 0,
      x: 740,
      y: 700,
    },
    {
      id: "src/start.ts",
      label: "start.ts",
      type: "module",
      language: "TypeScript",
      path: "src/start.ts",
      complexity: 1,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 11,
      dependencyCount: 1,
      dependentCount: 1,
      x: 850,
      y: 700,
    },
    {
      id: "src/styles.css",
      label: "styles.css",
      type: "module",
      language: "CSS",
      path: "src/styles.css",
      complexity: 2,
      changeFrequency: 0,
      linesOfCode: 0,
      riskScore: 16,
      dependencyCount: 0,
      dependentCount: 0,
      x: 80,
      y: 790,
    },
  ],
  edges: [
    {
      source: "src/components/ui/accordion.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/alert-dialog.tsx",
      target: "src/components/ui/button.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/components/ui/alert-dialog.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/alert.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/avatar.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/badge.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/breadcrumb.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/button.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/calendar.tsx",
      target: "src/components/ui/button.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/components/ui/calendar.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/card.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/carousel.tsx",
      target: "src/components/ui/button.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/components/ui/carousel.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/chart.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/checkbox.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/command.tsx",
      target: "src/components/ui/dialog.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/components/ui/command.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/context-menu.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/dialog.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/drawer.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/dropdown-menu.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/form.tsx",
      target: "src/components/ui/label.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/components/ui/form.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/hover-card.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/input-otp.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/input.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/label.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/menubar.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/navigation-menu.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/pagination.tsx",
      target: "src/components/ui/button.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/components/ui/pagination.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/popover.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/progress.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/radio-group.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/resizable.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/scroll-area.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/select.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/separator.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/sheet.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/sidebar.tsx",
      target: "src/components/ui/button.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/components/ui/sidebar.tsx",
      target: "src/components/ui/input.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/components/ui/sidebar.tsx",
      target: "src/components/ui/separator.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/components/ui/sidebar.tsx",
      target: "src/components/ui/skeleton.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/components/ui/sidebar.tsx",
      target: "src/components/ui/tooltip.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/components/ui/sidebar.tsx",
      target: "src/hooks/use-mobile.tsx",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/sidebar.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/skeleton.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/slider.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/switch.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/table.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/tabs.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/textarea.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/toggle-group.tsx",
      target: "src/components/ui/toggle.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/components/ui/toggle-group.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/toggle.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/components/ui/tooltip.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/lib/trace-store.ts",
      target: "src/lib/mock-data.ts",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/routeTree.gen.ts",
      target: "src/router.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/routeTree.gen.ts",
      target: "src/routes/__root.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/routeTree.gen.ts",
      target: "src/routes/analytics.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/routeTree.gen.ts",
      target: "src/routes/explore.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/routeTree.gen.ts",
      target: "src/routes/impact.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/routeTree.gen.ts",
      target: "src/routes/index.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/routeTree.gen.ts",
      target: "src/routes/sessions.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/routeTree.gen.ts",
      target: "src/start.ts",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/routes/__root.tsx",
      target: "src/lib/lovable-error-reporting.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/routes/analytics.tsx",
      target: "src/lib/mock-data.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/routes/analytics.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/routes/explore.tsx",
      target: "src/components/ui/button.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/routes/explore.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/routes/explore.tsx",
      target: "src/lib/mock-data.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/routes/impact.tsx",
      target: "src/components/ui/button.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/routes/impact.tsx",
      target: "src/lib/trace-store.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/routes/impact.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/routes/impact.tsx",
      target: "src/lib/mock-data.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/routes/index.tsx",
      target: "src/components/ui/avatar.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/routes/index.tsx",
      target: "src/components/ui/button.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/routes/index.tsx",
      target: "src/components/ui/textarea.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/routes/index.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/routes/sessions.tsx",
      target: "src/components/ui/avatar.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/routes/sessions.tsx",
      target: "src/components/ui/button.tsx",
      type: "import",
      weight: 0.8,
    },
    {
      source: "src/routes/sessions.tsx",
      target: "src/lib/trace-store.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/routes/sessions.tsx",
      target: "src/lib/utils.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/routes/sessions.tsx",
      target: "src/lib/mock-data.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/server.ts",
      target: "src/lib/error-capture.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/server.ts",
      target: "src/lib/error-page.ts",
      type: "call",
      weight: 0.8,
    },
    {
      source: "src/start.ts",
      target: "src/lib/error-page.ts",
      type: "call",
      weight: 0.8,
    },
  ],
  metadata: {
    totalFiles: 65,
    totalModules: 65,
    avgComplexity: 1.6,
    maxDepth: 0,
    lastAnalyzed: "2026-09-06T05:48:54.921Z",
  },
};
